apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdhSampleThisTime
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/ysoni-redhat/RHDH-Install-ArgoCD.git'
    targetRevision: main
    path: manifests
    directory:
      include: namespace.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
